{% set name = "aioitertools" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8b02facfbc9b0f1867739949a223f3d3267ed8663691cc95abd94e2c1d8c2b46

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - flit-core >=2,<4
    - typing_extensions >=3.7
  run:
    - python >=3.6
    - typing_extensions >=3.7

test:
  imports:
    - aioitertools
    - aioitertools.tests

about:
  home: https://github.com/jreese/aioitertools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: asyncio version of the standard multiprocessing module
  description: |
    Implementation of itertools, builtins, and more for AsyncIO and mixed-type
    iterables.
  doc_url: https://github.com/jreese/aioitertools
  dev_url: https://github.com/jreese/aioitertools

extra:
  recipe-maintainers:
    - nehaljwani
