travis:
  secure:
    BINSTAR_TOKEN: f+4sD4z3fh3Z4BYahny32XbYsCYu4FSno5Ko7B71paEh0r1QYU1aLQ0w3a5vhnICMn+aBFtKyZLmX0Ovqxyaj9OK9AfD8d5wBgwddBIab/18ACkTbDDZvhj+HIGEFhQk3195QzgjFlaVBh1hEMA1emJA+sSIm4ursVe0GoreR3OjvRfDFQO9CFx3xn+msb74sdzRtumrs8zugFpgg4QOTq3KY9JAi8ou2tw5YOUNeeTQLJVY7wxx9Za8M9xwU5NBBHS6H/r24kjPPppv+dV/lvoyXv7EJsgPUUkc9Z5TPGDsr/0+Ol+hZwieLTJlimIdzVz0xN4EOytfgBBCd2rMCeEPA0IGYxI64vXZ651HMS8hL1u5dPbC2fCn450wIX9WesqSJN+Sj9b7C+F/uAydJ/wJ/T/DPXorreC4tV3OTChZXrJ+NDKm+KhVK3wF1O1Uey1vy6LSisdCB5tbhbftxoDYu5rwXtd7peGq0dmY6aqNkkMPgzEe+I0vCAExiDyX4ym6ZkDAmX2DThUpCCiM1pzYJwCTX3oMRolmXbY5pAQIInXTDv6St0iS2F/L70dm6YIu/1tT8da4OAcuGw6aGcKsVEwXdi56WSFpDiCu6aXNB9ZyeIGjep43WD6+/T91bn6YVbKbNJoNd/E31mBsv39qc6VkFrqnIBx4j4dbK9I=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
